---
  - hosts: 127.0.0.1
    become: yes

    tasks:
    - name: Update package sources
      action: "{{ ansible_pkg_mgr }} update_cache=yes cache_valid_time=3600"

    - name: Install base packages
      action: "{{ ansible_pkg_mgr }} pkg={{ item }} state=present"
      with_items:
        - git
        - ruby
        - rake
        - rbenv
        - python-pip

    - name: Install 'bundler' with gem
      gem: name=bundler state=present


    - name: Install virtualbox and virtualbox-ext-pack
      apt: name={{ item }}
      with_items:
        - virtualbox
        - virtualbox-ext-pack
      tags: virtualbox

    - include: virtualbox_ppa.yml
      tags: virtualbox_ppa


    - name: Install vagrant
      apt: name=vagrant
      tags: vagrant

    - include: vagrant.yml
      vars:
        vagrant_version: 1.8.1
      tags: vagrant_from_web


    - include: docker.yml
      tags: docker

    - include: docker-compose.yml
      tags: docker-compose


    - include: deisctl.yml
      vars:
        deisclt_version: 1.13.0
      tags: deisctl

    - include: deis_client.yml
      vars:
        deisclt_version: 1.13.0
      tags: deisclient

    - include: fleetctl.yml
      vars:
        fleetctl_version: v0.11.7
      tags: fleetctl

    - include: kubectl.yaml
      vars:
        kubectl_version: v1.3.0
      tags: kubectl
