---
  - name: install deis client
    get_url:
      url: http://deis.io/deis-cli/install.sh
      dest: /tmp/deis-cli_install.sh
      mode: 0550

  - name: Run deis client install.sh
    shell: /tmp/deis-cli_install.sh {{ deisclt_version }}
    args:
      chdir: /usr/local/bin/
      creates: /usr/local/bin/deis

  - name: cleanup deis client
    file: path=/tmp/deis-cli_install.sh state=absent
