---
  - name: install deisctl
    get_url:
      url: http://deis.io/deisctl/install.sh
      dest: /tmp/deisctl_install.sh
      mode: 0550

  - name: Run deis install.sh
    shell: /tmp/deisctl_install.sh {{ deisclt_version }}
    args:
      chdir: /usr/local/bin/
      creates: /usr/local/bin/deisctl

  - name: cleanup
    file: path=/tmp/deisctl_install.sh state=absent
