---
  - name: Install facter for architecture recognition
    apt: name=facter

  - name: download fleetctl
    get_url:
      url: https://github.com/coreos/fleet/releases/download/{{ fleetctl_version }}/fleet-{{ fleetctl_version }}-{{ ansible_system | lower }}-{{ facter_architecture }}.tar.gz
      dest: /tmp/fleet-{{ fleetctl_version }}-{{ ansible_system | lower }}-{{ facter_architecture }}.tar.gz

  - name: unarchive fleetctl
    unarchive:
      src: /tmp/fleet-{{ fleetctl_version }}-{{ ansible_system | lower }}-{{ facter_architecture }}.tar.gz
      dest: /tmp/

  - name: install fleetctl
    copy:
      src: /tmp/fleet-{{ fleetctl_version }}-{{ ansible_system | lower }}-{{ facter_architecture }}/fleetctl
      dest: /usr/local/bin/fleetctl
      owner: root
      group: root
      mode: 0755

  - name: cleanup
    file: path=/tmp/fleet-{{ fleetctl_version }}-{{ ansible_system | lower }}-{{ facter_architecture }}.tar.gz state=absent

  - name: cleanup 2
    file: path=/tmp/fleet-{{ fleetctl_version }}-{{ ansible_system | lower }}-{{ facter_architecture }}/ state=absent
